# Generated by Django 3.0.4 on 2021-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QA_No', models.CharField(max_length=100)),
                ('OV', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQL_syntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.TextField(blank=True, max_length=1000, null=True)),
                ('sub', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='std_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Lv', models.IntegerField(default=1)),
                ('job', models.CharField(max_length=50)),
                ('tribe', models.CharField(max_length=50)),
                ('job_change_count', models.IntegerField(default=0)),
            ],
        ),
    ]
