# Generated by Django 3.0.4 on 2021-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_quest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_data',
            name='tribe',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
