# Generated by Django 3.0.4 on 2021-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_quest_app', '0002_sql_syntax_sub2'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(blank=True, max_length=1000, null=True)),
                ('sql_syn', models.TextField(blank=True, max_length=1000, null=True)),
                ('quest_table', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer_table', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.TextField(blank=True, max_length=1000, null=True)),
                ('h', models.TextField(blank=True, max_length=1000, null=True)),
                ('z', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
