# Generated by Django 3.0.4 on 2021-08-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='qa',
            name='quest',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
